'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function ConexaoProjeto({slug,projeto,publicacoes,decisoes,entregas,ventures,membros,chaves,podeGerenciar,podeDecidir,podePublicar}:{slug:string;projeto:any;publicacoes:any[];decisoes:any[];entregas:any[];ventures:any[];membros:any[];chaves:any[];podeGerenciar:boolean;podeDecidir:boolean;podePublicar:boolean}) {
  const router=useRouter(); const [mensagem,setMensagem]=useState(''); const [token,setToken]=useState(''); const [busy,setBusy]=useState(false);
  async function enviar(endpoint:string,dados:any){setBusy(true);setMensagem('');try{const r=await fetch(`/api/opera/projetos/${slug}/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dados)});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.token)setToken(d.token);setMensagem(endpoint==='decisoes'?'Decisão registrada. Aguardando confirmação do Construtor.':'Registro salvo.');router.refresh();}catch(e){setMensagem(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
  const form=(endpoint:string,extras:any={})=>(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();void enviar(endpoint,{...Object.fromEntries(new FormData(e.currentTarget)),...extras});};
  const atual=publicacoes[0]; const entrega=entregas[0];
  return <div className="op-form">
    {mensagem&&<p className="op-note" role="status">{mensagem}</p>}
    <section className="op-panel"><div className="op-section-title"><h2>Identidade compartilhada</h2><span>Uma construção, referências estáveis</span></div><p>ID da construção: <code>{projeto.construcao_id}</code></p><p>{projeto.venture_id?<a href={`/dashboard/ventures/${projeto.venture_id}`}>Abrir Venture vinculada ↗</a>:'Venture ainda não vinculada.'} · Processo: {projeto.processo_slug||'não definido'}</p>
    {podeGerenciar&&!projeto.venture_id&&<form onSubmit={form('gestao',{acao:'vincular'})}><div className="op-form-grid"><label>Venture do Comercial<select name="venture_id" required><option value="">Selecione</option>{ventures.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Identificador do processo<input name="processo_slug" required pattern="[a-z0-9][a-z0-9-]{1,60}" placeholder="emissao-cte" /></label></div><button className="op-button" disabled={busy}>Vincular identidade</button></form>}
    </section>
    {podeGerenciar&&<section className="op-panel"><h2>Memória do Cérebro</h2><p>{projeto.cerebro_construcao_id?`Construção vinculada: ${projeto.cerebro_construcao_id}`:'Se este banco já contém o schema opera, vincule a construção existente. Venture e processo precisam coincidir; o portal não cria outra identidade.'}</p>{!projeto.cerebro_construcao_id&&<form onSubmit={form('gestao',{acao:'cerebro'})}><label>ID da construção no Cérebro<input name="construcao" required/></label><button className="op-button" disabled={busy}>Vincular diário ao Cérebro</button></form>}</section>}
    <section className="op-panel"><div className="op-section-title"><h2>Da venda à entrega</h2><span>Compromisso versionado</span></div>
    {entrega?<><p>Versão {entrega.versao} · {entrega.aceito_em?'Aceita pela operação':'Aguardando aceite da operação'}</p>{['escopo','exclusoes','aceite','dependencias','capacidade'].map(k=><div key={k}><h3>{k}</h3><p style={{whiteSpace:'pre-wrap'}}>{entrega[k]}</p></div>)}{!entrega.aceito_em&&podeDecidir&&<button className="op-button" disabled={busy} onClick={()=>enviar('entrega',{aceitar:entrega.id})}>Aceitar esta versão da entrega</button>}</>:<p className="op-empty">Registre o combinado comercial e os critérios que a operação precisa confirmar.</p>}
    {podePublicar&&<details><summary>{entrega?'Propor uma nova versão':'Preparar compromisso de entrega'}</summary><form onSubmit={form('entrega')}><label>Escopo<textarea name="escopo" required defaultValue={entrega?.escopo||projeto.processo} /></label><label>O que não está incluído<textarea name="exclusoes" required defaultValue={entrega?.exclusoes} /></label><label>Critérios de aceite<textarea name="aceite" required defaultValue={entrega?.aceite} /></label><label>Dependências e riscos<textarea name="dependencias" required defaultValue={entrega?.dependencias} /></label><label>Responsável, capacidade e condição para início<textarea name="capacidade" required defaultValue={entrega?.capacidade} /></label><button className="op-button" disabled={busy}>Registrar versão para revisão</button></form></details>}
    <details><summary>Histórico do compromisso ({entregas.length})</summary>{entregas.map(e=><p key={e.id}>v{e.versao} · {e.criado_em} · autor {e.autor} · {e.aceito_em?`aceite ${e.aceito_por}`:'não aceita'}</p>)}</details></section>
    <section className="op-panel"><div className="op-section-title"><h2>Decidir sobre a evidência</h2><span>Conteúdo exato enviado pelo Construtor</span></div>
    {!atual&&<p className="op-empty">Conecte o Construtor para receber a primeira publicação.</p>}
    {atual?.artefatos?.map((a:any)=>{const d=decisoes.find(d=>d.proposta_id===a.propostaId);return <details className="op-response" key={a.chave}><summary>{a.chave} · {d?`${d.decisao} · ${d.estado}`:a.situacao}</summary><p className="op-stamp">SHA-256: {a.hash}</p><pre className="op-review-code">{a.conteudo}</pre>{d?<p>{d.motivo}<br/>Decidido por {d.autor}. {d.resultado||'O Construtor ainda não confirmou a aplicação.'}</p>:a.situacao==='proposta'&&podeDecidir&&<form onSubmit={form('decisoes',{publicacao:atual.id,propostaId:a.propostaId,hash:a.hash})}><label>Decisão<select name="decisao"><option value="aprovar">Aprovar</option><option value="recusar">Recusar</option></select></label><label>Motivo<textarea name="motivo" required minLength={10} maxLength={2000}/></label><label className="op-check"><input type="checkbox" required/> Revisei o conteúdo desta versão.</label><button className="op-button" disabled={busy}>Registrar decisão</button></form>}</details>})}
    </section>
    <section className="op-panel"><div className="op-section-title"><h2>Histórico de publicações</h2><span>Últimas 50 · preservadas no banco</span></div>{publicacoes.map(p=><details className="op-response" key={p.id}><summary>{p.snapshot.etapa} · {new Date(p.recebido_em).toLocaleString('pt-BR')}</summary><p>Origem: {p.autor}</p><p>Evento: {p.evento_id}</p><p>{p.snapshot.resumo}</p><pre className="op-review-code">{JSON.stringify(p.snapshot,null,2)}</pre></details>)}</section>
    {podeGerenciar&&<><section className="op-panel"><div className="op-section-title"><h2>Conectar o Construtor</h2><span>Credencial limitada a este projeto</span></div><p>Salve este manifesto como <code>.opera/portal.json</code> no repositório da solução. A credencial fica somente no ambiente.</p><pre className="op-review-code">{JSON.stringify({slug,construcaoId:projeto.construcao_id},null,2)}</pre><button className="op-button" disabled={busy} onClick={()=>enviar('gestao',{acao:'token'})}>Gerar credencial de 30 dias</button>{token&&<div className="op-note"><p>Copie agora. Não será exibida novamente. Configure OPERA_PORTAL_TOKEN.</p><code style={{overflowWrap:'anywhere'}}>{token}</code><button onClick={()=>setToken('')}>Ocultar</button></div>}<pre className="op-review-code">{'OPERA_PORTAL_TOKEN=<credencial no ambiente>\nnode bin/opera-portal.ts --dir /caminho/da/solucao --acompanhar'}</pre>{chaves.map(c=><p key={c.id}>Credencial {c.id.slice(0,8)} · até {c.expira_em} · {c.revogado_em?'revogada':<button disabled={busy} onClick={()=>enviar('gestao',{acao:'revogar',id:c.id})}>Revogar</button>}</p>)}</section>
    <section className="op-panel"><div className="op-section-title"><h2>Acesso da equipe</h2><span>Administradores e criador mantêm gestão</span></div>{membros.map(m=><p key={m.usuario}>{m.usuario} · {m.papel}</p>)}<form onSubmit={form('gestao',{acao:'membro'})}><label>ID do usuário ativo no Studio<input name="usuario" required/></label><label>Permissão<select name="papel"><option value="leitor">Ler</option><option value="operador">Ler e publicar</option><option value="revisor">Ler, publicar e decidir</option><option value="remover">Remover acesso</option></select></label><button className="op-button" disabled={busy}>Atualizar acesso</button></form></section>
    <section className="op-panel"><h2>Compartilhamento externo</h2><p>Links públicos não exigem convite. Documentos técnicos de revisão e decisões continuam internos.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void enviar('gestao',{acao:'visibilidade',painel_publico:f.has('painel'),colheita_publica:f.has('colheita')});}}><label className="op-check"><input name="painel" type="checkbox" defaultChecked={projeto.painel_publico}/> Liberar painel público</label><label className="op-check"><input name="colheita" type="checkbox" defaultChecked={projeto.colheita_publica}/> Liberar colheita pública</label><button className="op-button" disabled={busy}>Salvar compartilhamento</button></form></section></>}
  </div>;
}
