// Requires tests/opera.mock.ts and a local Next server configured against it.
// npm build/start or dev with the fixture environment, never a real database.
import puppeteer from "puppeteer";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
const output = await mkdtemp(join(tmpdir(), "opera-portal-qa-"));
const browser = await puppeteer.launch({ headless: true, executablePath: process.env.CHROME_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
const page = await browser.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.setRequestInterception(true);
page.on("request", r => {
  const url = new URL(r.url());
  if (["localhost", "127.0.0.1", "fonts.googleapis.com", "fonts.gstatic.com"].includes(url.hostname) || url.protocol === "data:") r.continue();
  else r.abort();
});
const base = "http://localhost:3100";
const text = () => page.evaluate(() => document.body.innerText);
try {
  await page.setViewport({ width: 1440, height: 1050, deviceScaleFactor: 1 });
  await page.goto(`${base}/opera`, { waitUntil: "networkidle0" });
  assert.match(page.url(), /\/login/);
  const claims = { sub: "00000000-0000-4000-8000-000000000001", exp: Math.floor(Date.now() / 1000) + 3600, aud: "authenticated", role: "authenticated" };
  const jwt = `${Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })).toString("base64url")}.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.fixture-signature`;
  const session = { access_token: jwt, refresh_token: "fixture-refresh", expires_at: claims.exp, expires_in: 3600, token_type: "bearer", user: { id: claims.sub, email: "operador@example.invalid", aud: "authenticated", role: "authenticated", app_metadata: {}, user_metadata: {} } };
  await page.setCookie({ name: "sb-127-auth-token", value: "base64-" + Buffer.from(JSON.stringify(session)).toString("base64url"), domain: "localhost", path: "/" });
  await page.goto(`${base}/dashboard/opera`, { waitUntil: "networkidle0" });
  assert.match(await text(), /O trabalho, à vista/);
  await page.screenshot({ path: join(output, "portal-desktop.png"), fullPage: true });
  await page.goto(`${base}/dashboard/opera/projeto-teste`, { waitUntil: "networkidle0" });
  assert.match(await text(), /Revisar as ocorrências/);
  await page.screenshot({ path: join(output, "construcao-desktop.png"), fullPage: true });
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
  await new Promise(resolve => setTimeout(resolve, 450));
  await page.screenshot({ path: join(output, "construcao-mobile.png"), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "sem overflow horizontal no mobile");
  await page.goto(`${base}/colheita/projeto-teste`, { waitUntil: "networkidle0" });
  await page.type('input[placeholder="Nome e sobrenome"]', "Pessoa de teste");
  await page.type("textarea", "O pedido chega e a equipe confere os campos.");
  await page.screenshot({ path: join(output, "colheita-mobile.png"), fullPage: true });
  await page.locator('::-p-text(Enviar respostas)').click();
  await page.waitForFunction(() => document.body.innerText.includes("Obrigado, Pessoa"));
  await page.goto(`${base}/dashboard/opera/projeto-teste`, { waitUntil: "networkidle0" });
  assert.match(await text(), /Pessoa de teste/);
  await page.goto(`${base}/painel/projeto-teste#motor`, { waitUntil: "networkidle0" });
  assert.match(await text(), /Motor determinístico/);
  await page.goto(`${base}/painel/oasis-cte#motor`, { waitUntil: "networkidle0" });
  assert.match(await text(), /Motor preservado/);
  assert.match(page.url(), /\/painel\/oasis-cte#motor/);
  await page.goto(`${base}/colheita/oasis-cte`, { waitUntil: "networkidle0" });
  assert.match(await text(), /OASIS/);
  assert.match(await text(), /TRAFLOG/);
  await page.goto(`${base}/colheita/projeto-inexistente`, { waitUntil: "networkidle0" });
  assert.doesNotMatch(await text(), /Quem está respondendo/);
  await page.setViewport({ width: 1440, height: 1050 });
  await page.goto(`${base}/dashboard/opera/novo`, { waitUntil: "networkidle0" });
  await page.type('[name="nome"]', "Projeto criado no teste");
  await page.type('[name="cliente"]', "Cliente fictício");
  await page.type('[name="slug"]', `novo-teste-${Date.now()}`);
  await page.type('[name="responsavel"]', "Operador de teste");
  await page.type('[name="processo"]', "Conferir e encaminhar pedidos da operação.");
  await page.click('[name="colheita_publica"]');
  await page.screenshot({ path: join(output, "novo-projeto.png"), fullPage: true });
  await page.locator('::-p-text(Criar projeto e seus espaços)').click();
  await page.waitForFunction(() => location.pathname.includes("/dashboard/opera/novo-teste-"));
  await page.waitForFunction(() => document.body.innerText.includes("Publicar o primeiro acompanhamento"));
  assert.match(await text(), /Publicar o primeiro acompanhamento/);
  assert.deepEqual(errors, [], "sem erros JavaScript nas páginas OPERA");
  console.log(`Browser QA passou. Capturas: ${output}`);
} finally { await browser.close(); }
